import clsx from 'clsx';

import {
	__experimentalToggleGroupControl as ToggleGroupControl,
	__experimentalToggleGroupControlOption as ToggleGroupControlOption,
} from '@wordpress/components';

import { hasBlockSupport } from '@wordpress/blocks';
import { __ } from '@wordpress/i18n';

import { cleanEmptyObject } from '../utils';

export function isQueryContextDisabled( { name } ) {
	return ! hasBlockSupport( name, 'unitone.queryContext' );
}

export function resetQueryContextFilter() {
	return {
		queryContext: undefined,
	};
}

export function QueryContextEdit( { attributes: { unitone }, setAttributes } ) {
	return (
		<ToggleGroupControl
			__next40pxDefaultSize
			__nextHasNoMarginBottom
			isBlock
			label={ __( 'Responsive basis for block-specific CSS', 'unitone' ) }
			help={ __(
				"Choose whether this block's specific CSS responds to the viewport width or the container width. This does not affect CSS generated by WordPress.",
				'unitone'
			) }
			value={
				'container' === unitone?.queryContext ? 'container' : 'media'
			}
			onChange={ ( value ) =>
				setAttributes( {
					unitone: cleanEmptyObject( {
						...unitone,
						queryContext:
							'container' === value ? 'container' : undefined,
					} ),
				} )
			}
		>
			<ToggleGroupControlOption
				label={ __( 'Viewport', 'unitone' ) }
				value="media"
			/>
			<ToggleGroupControlOption
				label={ __( 'Container', 'unitone' ) }
				value="container"
			/>
		</ToggleGroupControl>
	);
}

export function withQueryContextBlockProps( settings ) {
	const { attributes, name } = settings;

	if ( isQueryContextDisabled( { name } ) ) {
		return settings;
	}

	const queryContextLayout = clsx(
		settings.wrapperProps?.[ 'data-unitone-layout' ],
		{
			'@container': 'container' === attributes?.unitone?.queryContext,
		}
	);

	return {
		...settings,
		wrapperProps: {
			...settings.wrapperProps,
			'data-unitone-layout': queryContextLayout || undefined,
		},
	};
}
