import clsx from 'clsx';

import { ToggleControl } from '@wordpress/components';
import { hasBlockSupport } from '@wordpress/blocks';
import { __ } from '@wordpress/i18n';

import { HelpContainer } from '../components';
import { cleanEmptyObject, normalizeForToggleControl } from '../utils';
import { isContainerQueryContext } from '../../../utils/css-container';

export function isQueryContextDisabled( { name } ) {
	return ! hasBlockSupport( name, 'unitone.queryContext' );
}

export function resetQueryContextFilter() {
	return { queryContext: undefined };
}

export function getQueryContextEditLabel() {
	return __(
		'Base this block’s own responsive CSS on container width',
		'unitone'
	);
}

export function QueryContextEdit( { attributes: { unitone }, setAttributes } ) {
	const help = __(
		'This block’s responsive CSS switches according to the width of an ancestor container. An ancestor container is required. This does not affect CSS generated by WordPress.',
		'unitone'
	);

	return (
		<HelpContainer help={ help } layout="horizontal">
			<ToggleControl
				__nextHasNoMarginBottom
				label={ getQueryContextEditLabel() }
				checked={ isContainerQueryContext( unitone?.queryContext ) }
				onChange={ ( value ) =>
					setAttributes( {
						unitone: cleanEmptyObject( {
							...unitone,
							queryContext:
								normalizeForToggleControl( value ) || undefined,
						} ),
					} )
				}
			/>
		</HelpContainer>
	);
}

export function withQueryContextBlockProps( settings ) {
	const { attributes, name } = settings;

	if ( isQueryContextDisabled( { name } ) ) {
		return settings;
	}

	return {
		...settings,
		wrapperProps: {
			...settings.wrapperProps,
			'data-unitone-layout':
				clsx( settings.wrapperProps?.[ 'data-unitone-layout' ], {
					'@container': isContainerQueryContext(
						attributes?.unitone?.queryContext
					),
				} ) || undefined,
		},
	};
}
